language: bash
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.4

branches:
  except:
    - /^example-/

env:
  global:
    - MAKEFLAGS="-j8"

before_install:
  - make clean

before_script:
  - git version

script:
  - make test

notifications:
  email: false
