language: bash
jobs:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11.4
      install:
        - brew install grep
        - export PATH="/usr/local/opt/grep/libexec/gnubin:$PATH"

branches:
  except:
    - /^example-/

env:
  global:
    - MAKEFLAGS="-j8"

after_install:
  - make clean

before_script:
  - git version
  - grep --version

script:
  - make test

notifications:
  email: false
