language: bash
jobs:
  include:
    - os: linux
      dist: bitonic
    - os: osx
      osx_image: xcode11.4

branches:
  except:
    - /^example-/

before_install:
  - make clean

after_install:
  - git version

script:
  - make test

notification:
  email: false
