version: 1.0.{build}

branches:
  except:
    - /^example-/

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

image:
  - Visual Studio 2019
  - Ubuntu2004
  - macos

environment:
  MAKEFLAGS: -j8

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  install:
    - choco install make

-
  matrix:
    only:
      - image: macos

before_build:
  - make --version
  - git version
  - grep --version
  - make clean

build_script:
  - make test
