version: 1.0.{build}

branches:
  except:
    - /^example-/

skip_commits:
  message: /\[ci skip\]|\[skip ci\]/

image:
  - macos
  - Visual Studio 2022
  - Ubuntu2004

environment:
  MAKEFLAGS: -j8

for:
-
  matrix:
    only:
      - image: Visual Studio 2022

  install:
    - choco install make

before_build:
  - make --version
  - git version
  - grep --version
  - make clean

build_script:
  - make test
