#!/bin/bash

if [ -z "$RAW" ]; then
    RAW=
else
    RAW="$RAW"
fi

if [ -z "$GH_USE_HTTPS" ]; then
    GH_USE_HTTPS=
else
    GH_USE_HTTPS="$GH_USE_HTTPS"
fi

set -euo pipefail

usage()
{
    cat - <<EOF
git-gets
    [-v|--verbose|-q|--quiet]
    <url> | <user>/<repo>
    [<branch>|<sha1>]
    [[-o] <target>] [-F|--rm-rf]
    [--flat [--tag-file=VERSION]]
    [-j<N>] [-c]
EOF
}

git_new() {
    V="$(git version)"
    [[ "$V" =~ ^git[[:space:]]version[[:space:]]2\..\. ]] && return 1
    [[ "$V" =~ ^git[[:space:]]version[[:space:]]2\.1.\. ]] && return 1
    return 0
}

fakerealpath() {
    if [[ "$1" =~ ^/ ]]; then
        printf '%s' "$1"
    else
        printf '%s/%s' "$PWD" "$1"
    fi
}

QUIET=
VERBOSE=
FORCE_DIR=
OUTPUT=
FLAT=
TAG_FILE=
JOBS=
CONFIRM=
POSITIONAL=()
while [ $# -gt 0 ]; do
    key="$1"
    case "$key" in
        -h|--help)
            usage
            exit
            ;;
        -q|--quiet)
            QUIET=--quiet
            shift
            ;;
        -v|--verbose)
            VERBOSE=YES
            shift
            ;;
        -F|--rm-rf)
            FORCE_DIR=YES
            shift
            ;;
        -o|--output)
            OUTPUT="$2"
            shift
            shift
            ;;
        -o-)
            OUTPUT="-"
            shift
            ;;
        --flat)
            FLAT=YES
            shift
            ;;
        --tag-file)
            FLAT=YES
            TAG_FILE="$2"
            shift
            shift
            ;;
        -j)
            JOBS="$2"
            shift
            shift
            ;;
        -c|--confirm)
            CONFIRM=YES
            shift
            ;;
        *)
            if [[ "$1" =~ ^-j ]]; then
                JOBS="${1#-j}"
            else
                POSITIONAL+=("$1")
            fi
            shift
            ;;
    esac
done

if [ "${#POSITIONAL[@]}" -eq 0 ]; then
    echo "Error: Must specify <repo-url> (any git remote) or <user>/<repo> (GitHub)"
    exit 1
elif [ "${#POSITIONAL[@]}" -eq 1 ]; then
    BRANCH="HEAD"
elif [ "${#POSITIONAL[@]}" -eq 2 ]; then
    BRANCH="${POSITIONAL[1]}"
elif [ "${#POSITIONAL[@]}" -eq 3 ]; then
    if [ ! -z "$OUTPUT" ]; then
        echo "Error: Too many positional arguments?" >&2
        exit 1
    fi
    BRANCH="${POSITIONAL[1]}"
    OUTPUT="${POSITIONAL[2]}"
else
    echo "Error: Too many positional arguments?" >&2
    exit 1
fi

if [[ "${POSITIONAL[0]}" =~ ^https://github.com/ ]]; then
    GITHUB=YES
    GH_REPO="${POSITIONAL[0]#https://github.com/}"
    GH_REPO="${GH_REPO%.git}"
    REPO="${POSITIONAL[0]}"
elif [[ "${POSITIONAL[0]}" =~ ^git@github.com: ]]; then
    GITHUB=YES
    GH_REPO="${POSITIONAL[0]#git@github.com:}"
    GH_REPO="${GH_REPO%.git}"
    REPO="${POSITIONAL[0]}"
elif [[ "${POSITIONAL[0]}" =~ ^.*/.*/.*$ ]]; then
    REPO="${POSITIONAL[0]}"
else
    GITHUB=YES
    GH_REPO="${POSITIONAL[0]}"
    if [ ! -z "$GH_USE_HTTPS" ]; then
        REPO="https://github.com/${POSITIONAL[0]}.git"
    else
        REPO="git@github.com:${POSITIONAL[0]}.git"
    fi
fi

BASENAME="$(basename "$REPO")"
BASENAME="${BASENAME%.git}"
if [ -z "$OUTPUT" ]; then
    OUTPUT="$BASENAME"
fi

if [ ! -z "$FLAT" ]; then
    if [ -z "$TAG_FILE" ]; then
        TAG_FILE="VERSION"
    fi
else
    TAG_FILE=
fi

which git >/dev/null
if [ $? -ne 0 ]; then
    echo "Error: git(1) not found"
    exit 66
fi

git_new || ([ ! -z "$QUIET" ] && printf 'Warning: You should upgrade your git (currently %s)\n' "$(git version)" >&2)

if [ ! -z "$FORCE_DIR" ]; then
    FORCE=YES
fi
if [ ! "$OUTPUT" = '-' ]; then
    OUTPUT="$(fakerealpath "$OUTPUT")"
fi
if [ ! -z "$VERBOSE" ]; then
    printf 'RAW=%q\n' "$RAW" >&2
    printf 'FORCE_DIR=%q\n' "$FORCE_DIR" >&2
    printf 'OUTPUT=%q\n' "$OUTPUT" >&2
    printf 'FLAT=%q\n' "$FLAT" >&2
    printf 'TAG_FILE=%q\n' "$TAG_FILE" >&2
    printf 'JOBS=%q\n' "$JOBS" >&2
    printf 'CONFIRM=%q\n' "$CONFIRM" >&2
    printf 'GITHUB=%q\n' "$GITHUB" >&2
    printf 'GH_REPO=%q\n' "$GH_REPO" >&2
    printf 'REPO=%q\n' "$REPO" >&2
    printf 'BRANCH=%q\n' "$BRANCH" >&2
    printf 'BASENAME=%q\n' "$BASENAME" >&2
fi

WORK_DIR="$(realpath "$(mktemp -d)")"
finish() {
    cd /
    rm -rf "$WORK_DIR"
}
trap finish EXIT
cd "$WORK_DIR"

[ ! -z "$VERBOSE" ] && printf 'WORK_DIR=%q\n' "$WORK_DIR" >&2

got_dir() {
    set -e
    if [ "$OUTPUT" = "-" ]; then
        [ ! -z "$VERBOSE" ] && (cd "$(dirname "$1")" && ls -lhAR "$(basename "$1")" >&2)
        (cd "$(dirname "$1")" && tar c "$(basename "$1")")
    elif [ -d "$OUTPUT" ]; then
        if [ ! -z "$FORCE_DIR" ]; then
            [ -z "$QUIET" ] && printf 'Warning: Overriding directory %q\n' "$OUTPUT" >&2
            rm -rf "$OUTPUT" && mv "$1" "$OUTPUT"
        else
            mv "$1" "$OUTPUT"
        fi
    elif [ -f "$OUTPUT" ]; then
        if [ ! -z "$FORCE" ]; then
            [ -z "$QUIET" ] && printf 'Warning: Overriding file %q\n' "$OUTPUT" >&2
            rm -f "$OUTPUT" && mv "$1" "$OUTPUT"
        else
            printf 'Error: File %q exists\n' "$OUTPUT" >&2
            exit 1
        fi
    else
        mv "$1" "$OUTPUT"
    fi
    [ ! -z "$VERBOSE" ] && printf 'size used in /tmp = %s\n' "$(du -sh "$WORK_DIR")" >&2
    exit 0
}

got_repo() {
    set -e
    git --git-dir="$1/.git" config --bool core.bare false
    git --git-dir="$1/.git" config core.repositoryformatversion 0

    ARGS=(git reset --hard)
    [ ! -z "$QUIET" ] && ARGS+=(-q)
    [   -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" >&2)
    [ ! -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" 2>/dev/null >&2)
    [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)

    ARGS=(git submodule)
    [ ! -z "$QUIET" ] && ARGS+=(--quiet)
    ARGS+=(init)
    [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)
    [   -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" >&2)
    [ ! -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" 2>/dev/null >&2)

    awk -F '"' '/^\[submodule / { print $2; }' "$1/.git/config" | (
    while IFS= read -r line; do
        PA="$(git config --file "$1/.gitmodules" "submodule.$line.path")"
        URL="$(git config --file "$1/.git/config" "submodule.$line.url")"
        SSHA1="$(git --git-dir="$1/.git" ls-files -s "$PA" | cut -d ' ' -f2)"
        [ ! -z "$VERBOSE" ] && printf '%s %s %s %s\n' "$line" "$PA" "$URL" "$SSHA1">&2
        rmdir "$1/$PA"
        ARGS=("$0")
        [ ! -z "$VERBOSE" ] && ARGS+=(--verbose)
        [ ! -z "$QUIET" ] && ARGS+=(--quiet)
        ARGS+=(-o "$1/$PA" "$URL" "$SSHA1")
        if [ ! -z "$CONFIRM" ]; then
            PMT="$(printf 'Will clone %s from %s, proceed? (Y/n) ...' "$PA" "$URL")"
            while true; do
                read -p "$PMT" -n 1 -r <&2
                case "$REPLY" in
                    "")
                        [ -z "$QUIET" ] && printf '+++ %s %s %s\n' "$PA" "$URL" "$SSHA1">&2
                        [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)
                        env RAW=YES "${ARGS[@]}" 2>&1 | sed 's/^/    /' >&2
                        break
                        ;;
                    y|Y)
                        printf '\n' >&2
                        [ -z "$QUIET" ] && printf '+++ %s %s %s\n' "$PA" "$URL" "$SSHA1">&2
                        [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)
                        env RAW=YES "${ARGS[@]}" 2>&1 | sed 's/^/    /' >&2
                        break
                        ;;
                    n|N)
                        printf '\n' >&2
                        [ -z "$QUIET" ] && printf '%s %s %s %s\n' '---' "$PA" "$URL" "$SSHA1">&2
                        break
                        ;;
                    *)
                        printf '\n' >&2
                        ;;
                esac
            done
        else
            [ -z "$QUIET" ] && printf '+++ %s %s %s\n' "$PA" "$URL" "$SSHA1">&2
            env RAW=YES "${ARGS[@]}" 2>&1 | sed 's/^/    /' >&2
        fi
    done)
    # [ ! -z "$JOBS" ] && ARGS+=(--jobs "$JOBS")
    if [ -z "$RAW" ]; then
        ARGS=(git submodule)
        [ ! -z "$QUIET" ] && ARGS+=(--quiet)
        ARGS+=(absorbgitdirs)
        [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)
        [   -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" >&2)
        [ ! -z "$QUIET" ] && (cd "$1" && "${ARGS[@]}" 2>/dev/null >&2)
    fi
    [ ! -z "$FLAT" ] && mv "$1/.git" ".git"
    got_dir "$1"
}

# 0. git 2.20+ -> shallow + [filter] -> filter
if git_new; then
    mkdir -p "$BASENAME"
    ARGS=(git clone --bare)
    [ ! -z "$QUIET" ] && ARGS+=(-q)
    [ ! "$BRANCH" = "HEAD" ] && ARGS+=(--branch "$BRANCH")
    ARGS+=(--depth 1 --no-tags)
    ARGS+=(--filter blob:none)
    ARGS+=("$REPO" "$BASENAME/.git")
    [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)
    set +e
    if [ -z "$QUIET" ]; then
        "${ARGS[@]}" 2>&1 | tee clone.log >&2
        R="$?"
    else
        "${ARGS[@]}" 1>clone.log 2>&1
        R="$?"
    fi
    if [ "$R" -eq 0 ]; then
        set -e
        got_repo "$BASENAME"
    fi
    set -e
    if [ ! -z "$(grep 'warning: Could not find remote branch' clone.log)" ]; then
        ARGS=(git clone --mirror --filter tree:0)
        [ ! -z "$QUIET" ] && ARGS+=(-q)
        ARGS+=("$REPO" "$BASENAME/.git")
        [ ! -z "$VERBOSE" ] && (printf '%q ' "${ARGS[@]}" >&2; printf '\n'>&2)
        set +e
        "${ARGS[@]}"
        if [ "$?" -eq 0 ]; then
            SHA1="$(git --git-dir="$BASENAME/.git" rev-parse "$BRANCH")"
            if [ ! -z "$SHA1" ]; then
                [ -z "$QUIET" ] && printf 'Got SHA1: %q\n' "$SHA1" >&2
                set -e
                git --git-dir="$BASENAME/.git" update-ref --no-deref HEAD "$SHA1"
                got_repo "$BASENAME"
            fi
        fi
        set -e
    fi
    rm -rf "$BASENAME"
fi

printf 'Error: No viable method.\n' >&2
exit 3
